swagger: '2.0'
info:
  title: Book My Show API
  description: This is my BOOK MY SHOW API Documentation
  version: 1.0
  servers:
    -url: http://192.168.10.123:3000
schemes: [http]

#Return Users From get request
paths:
  /user/getuser:
    get:
      summary: All User.
      description: Get all Users Details
      responses:
        200: # status code
          description: Successul Response
          schema:
            type: string
            example: 'Users String'
        400:
          description: User Error
          schema:
            type: string
            example: 'Some Error '

  /user/create:
    post:
      summary: Adds a new user
      produces:
        - application/json
      consumes:
        - multipart/form-data
      parameters:
        - name: Name
          in: formData
          description: Name of the user
          required: true
          type: string
        - name: Email
          in: formData
          description: Email of the user
          required: true
          type: string
        - name: Password
          in: formData
          description: Password of the user
          required: true
          type: string
        - name: Contact
          in: formData
          description: Contact number of the user
          required: true
          type: string
        - name: Role
          in: formData
          description: Role of the user
          required: true
          type: string
          enum:
            - owner
            - user
      responses:
        200:
          description: User successfully created
        400:
          description: Bad request
        500:
          description: Internal server error

  /user/update:
    put:
      tags:
        - pet
      summary: Update an existing user
      description: Update an existing user by Id
      operationId: updateUser
      requestBody:
        description: Update an existent user
        content:
          application/json:
        required: true
      responses:
        200: # status code
          description: Successul Response
          schema:
            type: string
            example: 'Users String'
        400:
          description: User Error
          schema:
            type: string
            example: 'Some Error '
